### ISSUE TITLE
Cannot repair codes with 2 chunks in them

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/go-leopard#14]
```
goos: linux
goarch: amd64
pkg: github.com/celestiaorg/rsmt2d
cpu: 11th Gen Intel(R) Core(TM) i9-11900H @ 2.50GHz
BenchmarkRepair/RSGF8_1x1x256_ODS-16         	   98379	     12215 ns/op
BenchmarkRepair/LeopardFF8_1x1x256_ODS-16    	panic: runtime error: index out of range [1] with length 1

goroutine 53 [running]:
github.com/celestiaorg/go-leopard.Decode({0xc000108990?, 0x1, 0x0?}, {0xc0001089a8?, 0x1, 0xc00006dcc8?})
	/home/mus/go/pkg/mod/github.com/celestiaorg/go-leopard@v0.1.0/wrapper.go:171 +0x14a
github.com/celestiaorg/rsmt2d.leoRSFF8Codec.Decode({}, {0xc000108990?, 0x30?, 0x0?})
	/home/mus/Code/rsmt2d/leopard.go:26 +0x54
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).rebuildShares(0xc0003c8000, 0x0, {0xc000108990?, 0x2, 0x2})
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:234 +0x58
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).solveCrosswordRow(0xc0003c8000, 0x0, {0xc0004216e0, 0x2, 0x2}, {0xc000421710, 0x2, 0x2})
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:131 +0x1d4
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).solveCrossword(0xc0003c8000, {0xc0004216e0, 0x2, 0x2}, {0xc000421710, 0x2, 0x2})
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:83 +0xd6
github.com/celestiaorg/rsmt2d.(*ExtendedDataSquare).Repair(0xc00014ad80?, {0xc0004216e0, 0x2, 0x2}, {0xc000421710, 0x2, 0x2})
	/home/mus/Code/rsmt2d/extendeddatacrossword.go:66 +0x7a
github.com/celestiaorg/rsmt2d.BenchmarkRepair.func1(0xc00014ad80)
	/home/mus/Code/rsmt2d/extendeddatacrossword_test.go:209 +0x21c
testing.(*B).runN(0xc00014ad80, 0x1)
	/usr/local/go/src/testing/benchmark.go:193 +0x102
testing.(*B).run1.func1()
	/usr/local/go/src/testing/benchmark.go:233 +0x59
created by testing.(*B).run1
	/usr/local/go/src/testing/benchmark.go:226 +0x9c
exit status 2
FAIL	github.com/celestiaorg/rsmt2d	2.837s

```

**Comment by musalbas** [comment]
In the klauspost implementation it works ok.
